from typing import ContextManager, List


def cd(path: str) -> ContextManager[None]: ...
def is_super_path(path1: str, path2: str) -> bool: ...
def normjoin(path: str, *paths: List(str)) -> str: ...
def filename(path: str) -> str: ...
def fileexe(path: str) -> str: ...

class FileNameAndPath(object):
    def __init__(self ,file_path_and_name:str) -> None: ...
    def raw_file_path_and_name(self) -> str: ...
    def path(self) -> str: ...
    def exists(self) -> str: ...
    def file_name_tuple(self) -> tuple: ...
    def file_name(self) -> str: ...
    def only_suffix(self) -> str: ...
    def only_name(self) -> str: ...
    def only_path(self) -> str: ...

